FROM python:3-alpine

RUN adduser -D -S ansible && \
    pip install -U pip && \
    apk add --no-cache --virtual .build-deps \
      alpine-sdk libffi-dev openssl-dev && \
    apk add --no-cache openssh-client && \
    pip install ansible suitable && \
    apk del .build-deps

USER ansible
WORKDIR /etc/ansible
ENTRYPOINT ["ansible-playbook"]
CMD ["-h"]
