from ubuntu:18.04

COPY certs/out/monit.pem /etc/ssl/certs/

COPY setup.sh /usr/local/bin/
RUN ["setup.sh"]

COPY syschecks.json /etc/consul.d/
COPY syschecks.sh /usr/local/bin/
COPY random_filler_killer.sh /usr/local/bin/

COPY run.sh /usr/local/bin/
CMD ["run.sh"]
