FROM alpine:3.21 AS dockerize

ENV DOCKERIZE_VERSION v0.9.3
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && echo "**** fix for host id mapping error ****" \
    && chown root:root /usr/local/bin/dockerize

FROM google/cloud-sdk:alpine

SHELL ["/bin/ash", "-o", "pipefail", "-c"]
RUN apk add --no-cache --virtual .build-deps \
      alpine-sdk libffi-dev openssl-dev python3-dev py3-pip && \
    gcloud config configurations create emulator --quiet && \
    git clone https://github.com/googleapis/python-pubsub.git && \
    cd python-pubsub/samples/snippets && \
    pip3 install -r requirements.txt --break-system-packages

COPY --from=dockerize /usr/local/bin/dockerize /usr/local/bin/

COPY gcpemu_cpstst.sh /usr/local/bin/run.sh

ENTRYPOINT ["run.sh"]
