FROM google/cloud-sdk:alpine

EXPOSE 8081

RUN apk add --no-cache openjdk8-jre \
  && gcloud components install beta cloud-datastore-emulator --quiet

ENTRYPOINT ["gcloud","beta","emulators","datastore","start","--project=demo"]
CMD ["--host-port=0.0.0.0:8081"]
