version: '3.2'

services:

  gcpcbtemu:
    image: gcpcbtemu
    build:
      context: .
      dockerfile: Dockerfile_GCPCBTEMU
    container_name: gcpcbtemu
    hostname: gcpcbtemu
    ports:
      - "28086:8086"
    networks:
      - gcpemulators-demo

  gcpemuws:
    image: gcpemuws
    build:
      context: .
      dockerfile: Dockerfile_GCPEMUWS
    container_name: gcpemuws
    hostname: gcpemuws
    environment:
      - "BIGTABLE_EMULATOR_HOST=gcpcbtemu:8086"
    depends_on:
      - gcpcbtemu
    networks:
      - gcpemulators-demo

networks:
  gcpemulators-demo:
