version: '3.2'

services:

  motoserver:
    image: moto${MOTOTAG}
    container_name: motoserver
    hostname: motoserver
    build:
      context: .
      dockerfile: Dockerfile_MTSRVR
    ports:
      - "15000:5000"
    networks:
      - terraform-demo

  localstack:
    image: localstack/localstack${LSTKTAG}
    container_name: localstack
    hostname: localstack
    volumes:
      - "${TMPDIR:-/tmp/terraform}:/tmp/terraform"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "14566:4566"
      - "14571:4571"
      - "${PORT_WEB_UI-18080}:${PORT_WEB_UI-18080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock        
    networks:
      - terraform-demo

  terraformws:
    image: hashicorp/terraform${TFRMTAG}
    container_name: terraformws
    hostname: terraformws
    volumes:
      - ./config/terraform:/etc/terraform:ro
    entrypoint: ash
    command: "-c 'while true; do sleep 5; done'"
    networks:
      - terraform-demo

networks:
  terraform-demo:
