Vagrant.configure("2") do |config|

  config.vm.box_check_update = true
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus   = "1"
  end

  (1..3).each do |i|
    config.vm.define "consul#{format('%02d', i)}" do |consul|
      consul.vm.hostname = "consul#{format('%02d', i)}"
      consul.vm.network "private_network", ip: "192.168.50.#{i+2}"
    end
  end

  (1..1).each do |i|
    config.vm.define "bas#{format('%02d', i)}" do |bas|
      bas.vm.hostname = "bas#{format('%02d', i)}"
      bas.vm.network "private_network", ip: "192.168.50.#{i+12}"
    end
  end

end
