version: '3.2'

services:

#  chefserver:
#    image: quay.io/3ofcoins/chef-server:12.18.14
#    container_name: chefserver
#    hostname: chefserver
#    privileged: true
#    ports:
#      - "9080:80"
#      - "9443:443"
#    networks:
#      - chef-demo

  chefwrkstn:
    image: chefwrkstn${CFWSTAG}
    container_name: chefwrkstn
    hostname: chefwrkstn
    build:
      context: .
      dockerfile: Dockerfile_CWSUB1804
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - chef-demo

  tstsrvr1:
    image: phusionbsimgssh${PBISTAG}
    container_name: tstsrvr1
    hostname: tstsrvr1
    build:
      context: .
      dockerfile: Dockerfile_TSUB1804
    ports:
      - "2222:22"
    networks:
      - chef-demo

  tstsrvr2:
    image: phusionbsimgssh${PBISTAG}
    container_name: tstsrvr2
    hostname: tstsrvr2
    build:
      context: .
      dockerfile: Dockerfile_TSUB1804
    ports:
      - "2223:22"
    networks:
      - chef-demo

  tstsrvr3:
    image: phusionbsimgssh${PBISTAG}
    container_name: tstsrvr3
    hostname: tstsrvr3
    build:
      context: .
      dockerfile: Dockerfile_TSUB1804
    ports:
      - "2224:22"
    networks:
      - chef-demo

networks:
  chef-demo:
