FROM phusion/baseimage:0.11

RUN rm -f /etc/service/sshd/down
ADD ./keys/out/test.pub /tmp/test.pub
RUN cat /tmp/test.pub >> /root/.ssh/authorized_keys

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["/sbin/my_init"]
