# This image is published for public usage to
# https://hub.docker.com/r/richnusgeeks/terrier
FROM alpine:3.12
LABEL "com.richnusgeeks.vendor"="richnusgeeks"
LABEL "com.richnusgeeks.category"="utility"
LABEL version="latest"
LABEL description="docker based testing driver for terrier"

ENV TERRIER_VERSION 0.0.2
ENV TERRIER_SHA256 d1e24779fa2aa2111cec044d6594da612e97a97fccd3b22bcdd421e00640a8f4

SHELL ["/bin/ash", "-o", "pipefail", "-x", "-c"]
WORKDIR /tmp
RUN apk add --no-cache --virtual=cst-deps ca-certificates curl \
  && apk add --no-cache bash \
  && mkdir -p /etc/terrier \
  && curl -sSLk -o terrier "https://github.com/heroku/terrier/releases/download/${TERRIER_VERSION}/terrier-linux-amd64" \
  && chmod +x terrier \
  && echo "${TERRIER_SHA256}  terrier"|sha256sum -cs \
  && mv terrier /usr/local/bin \
  && curl -sSLk -o docker.tgz "https://download.docker.com/linux/static/stable/x86_64/$(curl -sSkL https://download.docker.com/linux/static/stable/x86_64/|grep '^ *<a'|grep docker|grep -v rootless|awk -F '\"' '{print $2}'|sort -nr|head -1)" \
  && tar zxvf docker.tgz \
  && mv docker/docker /usr/local/bin \
  && rm -rfv docker docker.tgz

WORKDIR /etc/terrier

ENTRYPOINT ["/usr/local/bin/terrier"]
CMD ["-h"]
