FROM alpine:3.10

RUN apk add --no-cache ca-certificates curl bash \
  && curl -sSLk -o /tmp/docker.tgz https://download.docker.com/linux/static/stable/x86_64/$(curl -sSkL https://download.docker.com/linux/static/stable/x86_64/|grep '^ *<a'|grep docker|grep -v rootless|awk -F '"' '{print $2}'|sort -nr|head -1) \
  && cd /tmp \
  && tar zxf docker.tgz \
  && mv docker/docker /usr/local/bin \
  && rm -rf docker docker.tgz \
  && curl -sSLk https://github.com/$(curl -sSLk https://github.com/aelsabbahy/goss/releases/latest|grep releases/download|grep linux-amd64|awk -F'"' '{print $2}') -o /usr/local/bin/goss \
  && curl -sSLk https://github.com/$(curl -sSLk https://github.com/aelsabbahy/goss/releases/latest|grep releases/download|grep linux-amd64|sed 's/goss-linux-amd64/dgoss/'|awk -F'"' '{print $2}') -o /usr/local/bin/dgoss \
  && chmod +x /usr/local/bin/*goss \
  && mkdir -p /etc/goss

WORKDIR /etc/goss/

ENTRYPOINT ["dgoss"]
CMD ["-h"]
