# This image is published for public usage to
# https://hub.docker.com/r/richnusgeeks/dgoss
FROM alpine:3.10
LABEL "com.richnusgeeks.vendor"="richnusgeeks"
LABEL version="latest"
LABEL description="dgoss test driver docker image"

SHELL ["/bin/ash", "-o", "pipefail", "-c"]
WORKDIR /tmp
RUN apk add --no-cache --virtual=goss-deps ca-certificates curl \
  && apk add --no-cache bash \
  && curl -sSLk -o /sbin/tini "https://github.com$(curl -sSLk https://github.com/krallin/tini/releases|grep tini-static|grep amd64|grep '<a href='|grep -v .asc|head -1|awk -F'\"' '{print $2}')" \
  && chmod +x /sbin/tini \
  && curl -sSLk -o /tmp/docker.tgz "https://download.docker.com/linux/static/stable/x86_64/$(curl -sSkL https://download.docker.com/linux/static/stable/x86_64/|grep '^ *<a'|grep docker|grep -v rootless|awk -F '\"' '{print $2}'|sort -nr|head -1)" \
  && tar zxf docker.tgz \
  && mv docker/docker /usr/local/bin \
  && rm -rf docker docker.tgz \
  && curl -sSLk "https://github.com/$(curl -sSLk https://github.com/aelsabbahy/goss/releases/latest|grep releases/download|grep linux-amd64|awk -F'\"' '{print $2}')" -o /usr/local/bin/goss \
  && curl -sSLk "https://github.com/$(curl -sSLk https://github.com/aelsabbahy/goss/releases/latest|grep releases/download|grep linux-amd64|sed 's/goss-linux-amd64/dgoss/'|awk -F'\"' '{print $2}')" -o /usr/local/bin/dgoss \
  && chmod +x /usr/local/bin/*goss \
  && mkdir -p /etc/goss \
  && apk del goss-deps

WORKDIR /etc/goss/

ENTRYPOINT ["tini", "--"]
CMD ["dgoss", "-h"]
