FROM phusion/baseimage:0.11
LABEL "com.richnusgeeks.vendor"="richnusgeeks"
LABEL version="0.11"
LABEL description="multiprocess with ssh server docker image"

COPY ./run_tstsrvr.sh /usr/local/bin/run.sh

RUN rm -f /etc/service/sshd/down \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["run.sh"]
