FROM python:3-alpine

RUN apk add --no-cache --virtual .build-deps \
    alpine-sdk libffi-dev openssl-dev \
 && pip install paramiko \
                testinfra \
 && mkdir -p /etc/testinfra \
             /etc/ssl/certs/test_servers \
 && apk del .build-deps

WORKDIR /etc/testinfra

ENTRYPOINT ["py.test"]
CMD ["-h"]
