FROM phusion/baseimage:0.11

COPY ./keys/out/test.pub /tmp/test.pub

RUN rm -f /etc/service/sshd/down \
  && cat /tmp/test.pub >> /root/.ssh/authorized_keys \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["/sbin/my_init"]
