version: '3.2'

services:

  hzcast1:
    image: hazelcast/hazelcast
    container_name: hzcast1
    hostname: hzcast1
    volumes:
      - ./hazelcast.xml:/opt/hazelcast/hazelcast.xml
      - hzcast1-data:/data
    ports:
      - "15701:5701"
      - "19999:9999"
      - "28080:8080"
    environment:
      - JAVA_OPTS=-XX:MaxDirectMemorySize=1G -Dhazelcast.jmx=true -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data -Dhazelcast.config=hazelcast.xml -Dhazelcast.http.healthcheck.enabled=true
      - MANCENTER_URL=http://hzcastmc:8080/hazelcast-mancenter -Dhazelcast.config=hazelcast.xml -Dhazelcast.http.healthcheck.enabled=true
      - MIN_HEAP_SIZE=1g
      - MAX_HEAP_SIZE=1g
      - PROMETHEUS_PORT=8080
    networks:
      - hzcast-demo

  hzcast2:
    image: hazelcast/hazelcast
    container_name: hzcast2
    hostname: hzcast2
    volumes:
      - ./hazelcast.xml:/opt/hazelcast/hazelcast.xml
      - hzcast2-data:/data
    ports:
      - "15702:5701"
      - "20000:9999"
      - "28081:8080"
    environment:
      - JAVA_OPTS=-XX:MaxDirectMemorySize=1G -Dhazelcast.jmx=true -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data -Dhazelcast.config=hazelcast.xml -Dhazelcast.http.healthcheck.enabled=true
      - MANCENTER_URL=http://hzcastmc:8080/hazelcast-mancenter
      - MIN_HEAP_SIZE=1g
      - MAX_HEAP_SIZE=1g
      - PROMETHEUS_PORT=8080
    networks:
      - hzcast-demo
  
  hzcast3:
    image: hazelcast/hazelcast
    container_name: hzcast3
    hostname: hzcast3
    volumes:
      - ./hazelcast.xml:/opt/hazelcast/hazelcast.xml
      - hzcast3-data:/data
    ports:
      - "15703:5701"
      - "20001:9999"
      - "28082:8080"
    environment:
      - JAVA_OPTS=-XX:MaxDirectMemorySize=1G -Dhazelcast.jmx=true -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data -Dhazelcast.config=hazelcast.xml -Dhazelcast.http.healthcheck.enabled=true
      - MANCENTER_URL=http://hzcastmc:8080/hazelcast-mancenter
      - MIN_HEAP_SIZE=1g
      - MAX_HEAP_SIZE=1g
      - PROMETHEUS_PORT=8080
    networks:
      - hzcast-demo

  hzcastmc:
    image: hazelcast/management-center
    container_name: hzcastmc
    hostname: hzcastmc
    volumes:
      - hzcastmc-data:/data
    ports:
      - "18080:8080"
    networks:
      - hzcast-demo

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    hostname: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "38080:8080"
    networks:
      - hzcast-demo

  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "19000:9000"
    networks:
      - hzcast-demo

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
    networks:
      - hzcast-demo

volumes:
  hzcastmc-data:
  hzcast1-data:
  hzcast2-data:
  hzcast3-data:
  portainer-data:
  prometheus-data:

networks:
  hzcast-demo:
