variable "ami_id" {}
variable "inst_type" {}
variable "key_name" {}
variable "subnet_id" {}
variable "sg_id" {}
variable "num_nds" {}
variable "hst_nme" {}
variable "hst_env" {}
variable "apps_pckd" {}
variable "hst_rle" {}
variable "root_size" {}
variable "swap_size" {}
variable "vol_size" {}
variable "zone_id" {}
variable "prov_scrpt" {}
variable "sub_dmn" {}
