FROM alpine:3.13 AS dockerize

ENV DOCKERIZE_VERSION v0.6.1
RUN apk add --update --no-cache ca-certificates tzdata \
  && wget --no-check-certificate https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && echo "**** fix for host id mapping error ****" \
  && chown root:root /usr/local/bin/dockerize

FROM curlimages/curl:latest
LABEL "com.richnusgeeks.vendor"="richnusgeeks"
LABEL "com.richnusgeeks.category"="utility"
LABEL version="latest"
LABEL description="docker based Echo webapp CRUD testbench"

COPY --from=dockerize /usr/local/bin/dockerize /usr/local/bin/
COPY wacrudtb.sh /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
