FROM jenkins/jenkins:2.138.1-alpine
#FROM jenkins/jenkins:2.138.2

#RUN curl -Sslk https://download.docker.com/linux/static/stable/x86_64/docker-18.06.1-ce.tgz -o docker-18.06.1-ce.tgz 
#RUN tar -zxvf docker-18.06.1-ce.tgz -C /usr/local/bin

ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

COPY docker /usr/local/bin/docker

COPY init.groovy /usr/share/jenkins/ref/init.groovy.d/init.groovy
 
COPY plugins.list /usr/share/jenkins/ref/plugins.list

RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.list

