FROM jenkins/jenkins:2.138.1-alpine
 
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
 
COPY init.groovy /usr/share/jenkins/ref/init.groovy.d/init.groovy
 
COPY plugins.list /usr/share/jenkins/ref/plugins.list

RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.list
