---
version: '3.2'

services:
  jenkins:
    image: jenkins-lts-auto:latest
    build:
      context: .
      dockerfile: Dockerfile_JenkinsAuto
    volumes:
      - jenkins_home_lts_auto:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
      - "8080:8080"
    extra_hosts:
      - "moby:127.0.0.1"
      - "localhost: 127.0.0.1"
    networks:
      - jenkins-demo

volumes:
  jenkins_home_lts_auto:

networks:
  jenkins-demo:
