FROM alpine:3.10

ENV GOPATH /go

RUN mkdir -p /go && \
    apk add --no-cache bash ca-certificates git go alpine-sdk && \
    go get -v github.com/AcalephStorage/consul-alerts && \
    mv /go/bin/consul-alerts /bin && \
    go get -v github.com/hashicorp/consul && \
    mv /go/bin/consul /bin && \
    rm -rf /go && \
    apk del --purge go git alpine-sdk

EXPOSE 9000
CMD ["consul-alerts"]
