---
- include: redhat.yml
  when: ansible_os_family|lower == 'redhat'

- include: debian.yml
  when: ansible_os_family|lower == 'debian'

- include: docker_compose.yml

- include: cadvisor.yml

- include: dckrbnchscrty.yml
