---
# https://docs.docker.com/install/linux/docker-ce/centos/

- name: redhat => install utility packages
  yum: name="{{docker_packages[ansible_os_family|lower]['utility']}}"
       state=present

# neither yum_repository nor get_url worked
- name: redhat => add stable repository
  shell: "yum-config-manager --add-repo {{docker_packages[ansible_os_family|lower]['repo']}}"
  when: ansible_distribution|lower != "amazon"

- name: redhat => install main packages
  yum: name="{{docker_packages[ansible_os_family|lower]['main']}}"
       state=present
  when: ansible_distribution|lower != "amazon"

- name: amazon-linux2 => install main packages
  shell: "amazon-linux-extras install -y docker"
  ignore_errors: yes
  when: ansible_distribution|lower == "amazon"

- name: redhat => start and enable docker service
  service: name=docker
           state=started
           enabled=true
