services:

  monitoror:
    image: monitoror/monitoror:${MTRRTAG:-latest}
    ports:
      - "38080:8080"
    environment:
      - "MO_CONFIG=/etc/config.json"
    restart: unless-stopped

networks:
  default:
    name: statuspage-demo
    external: true
