FROM bugy/script-server:latest
LABEL "com.richnusgeeks.vendor"="richnusgeeks"
LABEL "com.richnusgeeks.category"="utility"
LABEL version="latest"
LABEL description="script-server with docker cli"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get install --no-install-recommends curl -y \
  && curl -sSLk -o /tmp/docker.tgz "https://download.docker.com/linux/static/stable/x86_64/$(curl -sSkL https://download.docker.com/linux/static/stable/x86_64/|grep '^ *<a'|grep docker|grep -v rootless|awk -F '"' '{print $2}'|sort -nr|head -1)" \
  && cd /tmp \
  && tar zxf docker.tgz \
  && mv docker/docker /usr/local/bin \
  && rm -rf docker docker.tgz \
  && apt-get remove curl -y \
  && apt-get clean \
  && echo -e 'test:{SHA}qUqP5cyxm6YcTAhz05Hph5gvu9M=\nadmin:{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc=' > /etc/.htpasswd
