version: '2.4'

services:

  scriptserver:
    image: script-server:${SCPTSRVR:-latest}
    build:
      context: .
      dockerfile: Dockerfile_ScriptServer
    container_name: scriptserver
    hostname: scriptserver
    ports:
      - "55000:5000"
    volumes:
#      - ../configs/conf.json:/app/conf/conf.json:ro
      - ../configs/runners/:/app/conf/runners/:ro
      - ../configs/scripts/:/app/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    mem_limit: 512m
    networks:
      - scriptserver-demo
    restart: unless-stopped

networks:
  scriptserver-demo:
