# cat cloud-config.yaml|multipass launch -n test --cloud-init -
# ssh -oStrictHostKeyChecking=no ubuntu@test.local
# multipass delete test
# multipass purge
# ssh-keygen -R test.localhost
#cloud-config
users:
  - default
  - name: ubuntu
    gecos: Ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh_import_id: None
    lock_passwd: true
    ssh_authorized_keys:
      - <public key>
package_update: true
package_upgrade: true
packages:
  - avahi-daemon
write_files:
  - content: |
      set daemon 10
      set log /var/log/monit.log

      set mail-format { from: monit@richnusgeeks.demo }

      set httpd port 2812 and
        use address 0.0.0.0
        allow localhost
        allow 0.0.0.0/0
        allow admin:monit
        allow guest:guest readonly

      include /opt/monit/monit.d/*
    path: /opt/monit/conf/monitrc
    owner: root:root
    permissions: '0600'
  - content: |
      check filesystem rootfs with path /
        if space usage > 90% then alert
        if inode usage > 90% then alert
    path: /opt/monit/monit.d/spaceinode
    owner: root:root
    permissions: '0600'
runcmd:
  - [ wget, "https://mmonit.com/monit/dist/binary/5.27.0/monit-5.27.0-linux-x64.tar.gz", -O, monit.tgz ]
  - [ tar, zxvf, monit.tgz ]
  - [ mkdir, /opt/monit/bin ]
  - [ cp, monit-5.27.0/bin/monit, /opt/monit/bin/monit ]
  - [ rm, -rfv, monit.tgz, monit-5.27.0 ]
  - /opt/monit/bin/monit -c /opt/monit/conf/monitrc
output:
  init:
    output: "> /var/log/cloud-init.out"
    error: "> /var/log/cloud-init.err"
  config: "tee -a /var/log/cloud-config.log"
  final:
    - ">> /var/log/cloud-final.out"
    - "/var/log/cloud-final.err"
