services:

  vigil:
    image: vigilsci:${VGILTAG:-v1.27.0}
    ports:
      - "48080:8080"
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:${OSRHTAG:-latest}
    environment:
      - "discovery.type=single-node"
    restart: unless-stopped

  kafka:
    image: apache/kafka-native
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    restart: unless-stopped

  redis:
    image: redis:${RDSSTAG:-latest}
    command: "redis-server --save 60 1 --loglevel warning"
    restart: unless-stopped

networks:
  default:
    name: statuspage-demo
    external: true
