---
- name: render goss spark master test
  template: src="goss_sparkmaster.yaml.j2"
            dest="{{ goss_binary['configad_location'] }}/goss_spark.yaml"
  notify:
    - restart goss service
  when: ansible_hostname | regex_search("^spark0")

- name: render goss spark worker test
  template: src="goss_sparkworker.yaml.j2"
            dest="{{ goss_binary['configad_location'] }}/goss_spark.yaml"
  notify:
    - restart goss service
  when: ansible_hostname | regex_search("^spark[1-9]")
