version: '2.4'

services:

  mattermost:
    image: mattermost-preview:${MMPWTAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile_Mattermost
    extra_hosts:
      - "dockerhost:127.0.0.1"
    container_name: mattermost-preview
    #    hostname: dockerhost
    ports:
      - "8065:8065"
    mem_limit: 500m
    restart: always
    networks:
      - mattermost-demo

networks:
  mattermost-demo:
