FROM alpine:3.12 AS dockerize

ENV DOCKERIZE_VERSION v0.6.1
RUN wget --no-check-certificate https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && echo "**** fix for host id mapping error ****" \
    && chown root:root /usr/local/bin/dockerize

FROM alpine:3.12

ENV GRPCURL_VERSION 1.6.1
COPY --from=dockerize /usr/local/bin/dockerize /usr/local/bin/

SHELL ["/bin/ash", "-o", "pipefail", "-c"]
WORKDIR /tmp
RUN wget --no-check-certificate https://github.com/fullstorydev/grpcurl/releases/download/v${GRPCURL_VERSION}/grpcurl_${GRPCURL_VERSION}_linux_x86_64.tar.gz \
  && tar zxvf grpcurl_${GRPCURL_VERSION}_linux_x86_64.tar.gz \
  && mv grpcurl /usr/local/bin/ \
  && rm -f /tmp/*

ENTRYPOINT ["/usr/local/bin/grpcurl"]
CMD ["-help"]
