FROM golang:1.14-alpine3.12 AS builder

ENV TLGOSPLS_VERSION 0.27.0

SHELL ["/bin/ash", "-o", "pipefail", "-c"]
WORKDIR /tmp
RUN wget --no-check-certificate https://github.com/temporalio/go-samples/archive/v${TLGOSPLS_VERSION}.zip \
  && unzip v${TLGOSPLS_VERSION}.zip \
  && rm -f v${TLGOSPLS_VERSION}.zip

WORKDIR /tmp/go-samples-${TLGOSPLS_VERSION}/helloworld/worker
COPY ./worker.go .
RUN rm main.go \
  && go build \
  && cp worker /usr/local/bin

WORKDIR /tmp/go-samples-${TLGOSPLS_VERSION}/helloworld/starter
COPY ./starter.go .
RUN rm main.go \
  && go build \
  && cp starter /usr/local/bin

FROM alpine:3.12 AS dockerize

ENV DOCKERIZE_VERSION v0.6.1
RUN wget --no-check-certificate https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && echo "**** fix for host id mapping error ****" \
    && chown root:root /usr/local/bin/dockerize

FROM alpine:3.12 AS tlacptst

RUN apk add --update --no-cache ca-certificates tzdata

# set up nsswitch.conf for Go's "netgo" implementation
# https://github.com/gliderlabs/docker-alpine/issues/367#issuecomment-424546457
RUN test ! -e /etc/nsswitch.conf && echo 'hosts: files dns' > /etc/nsswitch.conf

COPY --from=dockerize /usr/local/bin/dockerize /usr/local/bin/
COPY --from=builder /usr/local/bin/worker /usr/local/bin/worker
COPY --from=builder /usr/local/bin/starter /usr/local/bin/starter
