version: '2.4'

services:

   ansible:
     image: ansible${ANSLTAG}
     build:
       context: .
       dockerfile: Dockerfile_Ansible
     volumes:
       - ../../Common/ansible:/etc/ansible:ro
     command: main.yml -t apply_elasticsearch
     mem_limit: 500m
#     network_mode: host
networks:
  default:
    external:
      name: cldinabox-demo
