version: '2.4'

services:

  bootlose:
    image: bootloose${FTLSTAG}
    container_name: bootloosestop
    build:
      context: .
      dockerfile: Dockerfile_Bootloose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./bootloose.cfg:/etc/bootloose.cfg:ro
    command: stop
    mem_limit: 500m
#    networks:
#      - bootloose-demo

#networks:
#  bootloose-demo:
networks:
  default:
    external:
      name: cldinabox-demo
