FROM alpine:3.20
LABEL "com.richnusgeeks.vendor"="richnusgeeks"
LABEL "com.richnusgeeks.category"="utility"
LABEL version="latest"
LABEL description="docker based bootloose test driver"

SHELL ["/bin/ash", "-o", "pipefail", "-c"]
RUN apk add --no-cache ca-certificates curl openssh bash \
  && curl -sSLk -o /tmp/docker.tgz "https://download.docker.com/linux/static/stable/x86_64/$(curl -sSkL https://download.docker.com/linux/static/stable/x86_64/|grep '^ *<a'|grep docker|grep -v rootless|awk -F '"' '{print $2}'|sort -nr|head -1)" \
  && cd /tmp \
  && tar zxf docker.tgz \
  && mv docker/docker /usr/local/bin \
  && rm -rf docker docker.tgz \
  && mkdir -p /var/lib/bootloose \
  && curl -sSLk "https://github.com/k0sproject/bootloose/releases/download/$(curl -sSLk https://github.com/k0sproject/bootloose/releases 2>&1|grep releases|grep tag/|awk '{print $7}'|awk -F '"' '{print $2}'|awk -F'/' '{print $NF}'|head -1)/bootloose-linux-amd64" -o /usr/local/bin/bootloose \
  && chmod +x /usr/local/bin/bootloose

COPY bootloose_run.sh /usr/local/bin/run.sh
COPY render_bootloose_config.sh /usr/local/bin/rndrftlscnfg
WORKDIR /var/lib/bootloose

ENTRYPOINT ["run.sh"]
CMD ["-h"]
