version: '2.4'

services:

  footlose:
    image: footloose${FTLSTAG}
    container_name: footloosestop
    build:
      context: .
      dockerfile: Dockerfile_Footloose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./footloose.yaml:/tmp/footloose.yaml:ro
    command: stop
    mem_limit: 500m
#    networks:
#      - footloose-demo

#networks:
#  footloose-demo:
networks:
  default:
    external:
      name: cldinabox-demo
