version: '2.4'

services:

  footlose:
    image: footloose${FTLSTAG}
    container_name: footloosecreate
    build:
      context: .
      dockerfile: Dockerfile_Footloose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./footloose.cfg:/etc/footloose.cfg:ro
    command: create
    mem_limit: 500m
#    networks:
#      - footloose-demo

#networks:
#  footloose-demo:
networks:
  default:
    external:
      name: cldinabox-demo
